//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wood_Notes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotes
    {
        public int IdNota { get; set; }
        public string Titulo { get; set; }
        public string Contenido { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
