//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wood_Notes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotes
    {
        public int idNota { get; set; }
        public string titulo { get; set; }
        public string contenido { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> modificacion { get; set; }
        public Nullable<int> caracteres { get; set; }
        public Nullable<int> peso { get; set; }
        public int idUsers { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
